#/run/numberOfThreads 100

/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/gps/particle gamma
/gps/ene/mono 5 MeV

#/gps/pos/type Plane
/gps/pos/type Point
#/gps/pos/shape Circle
#/gps/pos/radius 0.635 cm

/gps/direction 0 0 1

/gps/ang/type cos
/gps/ang/rot1 -1 0 0
/gps/ang/mintheta 0. deg
/gps/ang/maxtheta 90. deg
/gps/ang/minphi 0. deg
/gps/ang/maxphi 360. deg

/gps/pos/centre 0 0 -10 cm

/run/printProgress 100
/run/beamOn 1000